--INSERT INTO STUDENT_INFO (stud_id, stud_name) VALUES(1, 'ABC');
--INSERT INTO STUDENT_INFO (stud_id, stud_name) VALUES(2, 'BCD');
--INSERT INTO STUDENT_INFO (stud_id, stud_name) VALUES(3, 'CDE');
--INSERT INTO STUDENT_INFO (stud_id, stud_name) VALUES(4, 'EFG');
--INSERT INTO STUDENT_INFO (stud_id, stud_name) VALUES(5, 'FGH');